//! The F2 transcendental accuracy harness (`fexp`/`fln`/`fpow` — class
//! **approximate**, the amendment's §F2). Unlike `f32_ops.rs`, rustc is NOT the
//! oracle here — rustc's transcendentals are platform libm, the thing being
//! escaped. Two references from `tests/data/f32_trans_golden.json` (generated by
//! `tests/data/gen_f32_trans_golden.py`, offline mpmath at 96-bit precision):
//!
//! - `sim_bits` — the kernel algorithm simulated host-side in correctly-rounded
//!   f32 steps. Every kernel op is a correctly-rounded F0 op, so the kernel must
//!   match this **bit-exactly** — asserted on all four executors (Spectrum, Cell,
//!   IR interpreter, RV32) via the chunked driver, which is also the cross-target
//!   determinism battery.
//! - `true_bits` — the correctly-rounded result (MPFR-class ground truth). The
//!   declared ULP bound is measured against this; `golden_ulp_claims_hold`
//!   re-verifies the JSON's own bound claims host-side, so a stale or hand-edited
//!   table can't smuggle a looser contract.
//!
//! Measured (2026-07-11): fexp max 1 ulp, fln max 1 ulp, fpow max 40 ulp over
//! |y·ln x| ≤ 60; fsin/fcos max ABSOLUTE error 2⁻²⁴ over |x| ≤ 8192 (near trig
//! zeros at large |x|, Cody–Waite reduction error is a fixed absolute quantity,
//! so relative ULP diverges there for every non-Payne-Hanek f32 trig — the
//! honest bound is absolute); fatan2 max 2 ulp. Bounds declared from
//! measurement; the consuming cells' manifests carry the same numbers in
//! `//! accuracy:` headers.

use crate::harness::{run_program_banked, run_program_pruned};

const GOLDEN: &str = include_str!("../data/f32_trans_golden.json");

enum Bound {
    Ulp(u32),
    Abs(f64),
}

struct Bank {
    name: &'static str,
    bound: Bound,
    /// `(args, sim_bits, true_bits)` — 1 or 2 args.
    cases: Vec<(Vec<u32>, u32, u32)>,
}

fn load() -> Vec<Bank> {
    let v: serde_json::Value = serde_json::from_str(GOLDEN).expect("golden json parses");
    ["fexp", "fln", "fpow", "fsin", "fcos", "fatan2"]
        .iter()
        .map(|&name| {
            let b = &v[name];
            let cases = b["cases"]
                .as_array()
                .unwrap()
                .iter()
                .map(|c| {
                    let row: Vec<u32> = c
                        .as_array()
                        .unwrap()
                        .iter()
                        .map(|x| x.as_u64().unwrap() as u32)
                        .collect();
                    let (args, tail) = row.split_at(row.len() - 2);
                    (args.to_vec(), tail[0], tail[1])
                })
                .collect();
            let bound = match b["bound_kind"].as_str().unwrap() {
                "ulp" => Bound::Ulp(b["bound"].as_u64().unwrap() as u32),
                _ => Bound::Abs(b["bound"].as_f64().unwrap()),
            };
            Bank { name, bound, cases }
        })
        .collect()
}

fn bank<'a>(banks: &'a [Bank], name: &str) -> &'a Bank {
    banks.iter().find(|b| b.name == name).unwrap()
}

fn ord32(x: u32) -> u32 {
    if x >> 31 == 0 {
        x | 0x8000_0000
    } else {
        0x8000_0000 - (x & 0x7FFF_FFFF)
    }
}

fn ulp_dist(a: u32, b: u32) -> u32 {
    let nan = |x: u32| x & 0x7FFF_FFFF > 0x7F80_0000;
    if nan(a) && nan(b) {
        return 0;
    }
    ord32(a).abs_diff(ord32(b))
}

fn call_expr(name: &str, args: &[u32]) -> String {
    match args {
        [a] => format!("{name}({a}u32)"),
        [a, b] => format!("{name}({a}u32, {b}u32)"),
        _ => unreachable!(),
    }
}

/// The kernel must reproduce the simulation bit-for-bit, chunked like
/// `f32_ops::run_bank`; a bad chunk re-runs singly to name the divergence.
/// `run_program_pruned` runs all four executors and asserts they agree, so this
/// is simultaneously the cross-target determinism battery.
fn run_sim_bank(name: &str, cases: &[(Vec<u32>, u32, u32)]) {
    for chunk in cases.chunks(8) {
        let mut body = String::from("fn f() -> u16 { let mut bad = 0u16;\n");
        for (args, sim, _) in chunk {
            body.push_str(&format!(
                "if {} != {sim}u32 {{ bad = bad + 1u16; }}\n",
                call_expr(name, args)
            ));
        }
        body.push_str("bad }\n");
        let src = format!("{body}{}", rustz80::F32_KERNELS);
        if run_program_pruned(&src, "f") != 0 {
            for (args, sim, truth) in chunk {
                let single = format!(
                    "fn f() -> u16 {{ let mut bad = 0u16; if {} != {sim}u32 {{ bad = 1u16; }} bad }}\n{}",
                    call_expr(name, args),
                    rustz80::F32_KERNELS
                );
                assert_eq!(
                    run_program_pruned(&single, "f"),
                    0,
                    "{name}({args:08X?}) diverged from the f32 simulation \
                     (expected bits 0x{sim:08X}, ground truth 0x{truth:08X})"
                );
            }
            panic!("chunk counted failures but every single passed — chunking bug");
        }
    }
}

#[test]
fn fexp_matches_simulation_on_all_targets() {
    let banks = load();
    let b = bank(&banks, "fexp");
    run_sim_bank(b.name, &b.cases);
}

#[test]
fn fln_matches_simulation_on_all_targets() {
    let banks = load();
    let b = bank(&banks, "fln");
    run_sim_bank(b.name, &b.cases);
}

#[test]
fn fpow_matches_simulation_on_all_targets() {
    let banks = load();
    let b = bank(&banks, "fpow");
    run_sim_bank(b.name, &b.cases);
}

#[test]
fn fsin_matches_simulation_on_all_targets() {
    let banks = load();
    let b = bank(&banks, "fsin");
    run_sim_bank(b.name, &b.cases);
}

#[test]
fn fcos_matches_simulation_on_all_targets() {
    let banks = load();
    let b = bank(&banks, "fcos");
    run_sim_bank(b.name, &b.cases);
}

#[test]
fn fatan2_matches_simulation_on_all_targets() {
    let banks = load();
    let b = bank(&banks, "fatan2");
    run_sim_bank(b.name, &b.cases);
}

/// The accuracy contract: every golden case's simulation (== kernel, by the bank
/// tests above) sits within the declared bound of the correctly-rounded truth —
/// ULP for exp/ln/pow/atan2, absolute error for sin/cos (see the module doc).
/// Recomputed here so the JSON can't claim a bound its own rows violate.
#[test]
fn golden_ulp_claims_hold() {
    for b in load() {
        match b.bound {
            Bound::Ulp(bound) => {
                let mut max = 0u32;
                for (args, sim, truth) in &b.cases {
                    let d = ulp_dist(*sim, *truth);
                    assert!(
                        d <= bound,
                        "{}({args:08X?}): sim 0x{sim:08X} is {d} ulp from truth \
                         0x{truth:08X} (declared bound {bound})",
                        b.name
                    );
                    max = max.max(d);
                }
                // The bound is measured+1 — a table regenerated with a better
                // kernel must tighten it, and one that got worse must fail here,
                // not silently relax.
                assert!(
                    max + 1 == bound || max == bound,
                    "{}: bound {bound} is not measured({max})+1 — regenerate the table",
                    b.name
                );
            }
            Bound::Abs(bound) => {
                for (args, sim, truth) in &b.cases {
                    let (fs, ft) = (f32::from_bits(*sim), f32::from_bits(*truth));
                    if fs.is_nan() && ft.is_nan() {
                        continue;
                    }
                    let d = (fs as f64 - ft as f64).abs();
                    assert!(
                        d <= bound,
                        "{}({args:08X?}): sim 0x{sim:08X} is {d:e} from truth \
                         0x{truth:08X} (declared abs bound {bound:e})",
                        b.name
                    );
                }
            }
        }
    }
}

/// The IEEE/Rust special-value pin table — hand-derived exact bits, independent
/// of the golden JSON (and covering the `fpow` specials the sampled bank omits).
#[test]
fn f32_trans_special_pins() {
    const INF: u32 = 0x7F80_0000;
    const NINF: u32 = 0xFF80_0000;
    const NAN: u32 = 0x7FC0_0000;
    const ONE: u32 = 0x3F80_0000;
    const TWO: u32 = 0x4000_0000;
    const HALF: u32 = 0x3F00_0000;
    const NEG_TWO: u32 = 0xC000_0000;
    let pins: &[(String, u32)] = &[
        // fexp: NaN→NaN, +Inf→+Inf, -Inf→0, ±0→1, clamp bands
        (format!("fexp({NAN}u32)"), NAN),
        (format!("fexp({INF}u32)"), INF),
        (format!("fexp({NINF}u32)"), 0),
        ("fexp(0u32)".to_string(), ONE),
        ("fexp(2147483648u32)".to_string(), ONE), // -0
        ("fexp(0x42B17218u32)".to_string(), INF), // x ≥ 88.722839 → +Inf
        ("fexp(0xC2CFF1B5u32)".to_string(), 0),   // x ≤ -103.972084 → +0
        // fln: NaN→NaN, ±0→-Inf, x<0→NaN, +Inf→+Inf, ln(1)=+0 exactly
        (format!("fln({NAN}u32)"), NAN),
        ("fln(0u32)".to_string(), NINF),
        ("fln(2147483648u32)".to_string(), NINF),
        (format!("fln({NEG_TWO}u32)"), NAN),
        (format!("fln({NINF}u32)"), NAN),
        (format!("fln({INF}u32)"), INF),
        (format!("fln({ONE}u32)"), 0),
        // fpow: the Rust powf pins
        (format!("fpow({NAN}u32, 0u32)"), ONE), // NaN^0 = 1
        (format!("fpow({ONE}u32, {NAN}u32)"), ONE), // 1^NaN = 1
        (format!("fpow({TWO}u32, 0u32)"), ONE),
        (format!("fpow({NEG_TWO}u32, {HALF}u32)"), NAN), // negative base → NaN (documented)
        (format!("fpow(0u32, {TWO}u32)"), 0),            // 0^y>0 = +0
        (format!("fpow(0u32, {NEG_TWO}u32)"), INF),      // 0^y<0 = +Inf
        (format!("fpow({INF}u32, {TWO}u32)"), INF),
        (format!("fpow({INF}u32, {NEG_TWO}u32)"), 0),
        (format!("fpow({TWO}u32, {INF}u32)"), INF),
        (format!("fpow({HALF}u32, {INF}u32)"), 0),
        (format!("fpow({TWO}u32, {NINF}u32)"), 0),
        // fsin/fcos: ±0 pins, NaN/±Inf → NaN (IEEE), and the declared-domain wall
        // (|x| > 8192 → NaN, deterministic — never a silently-degraded value)
        ("fsin(0u32)".to_string(), 0),
        ("fsin(2147483648u32)".to_string(), 0x8000_0000), // sin(-0) = -0
        (format!("fsin({INF}u32)"), NAN),
        (format!("fsin({NAN}u32)"), NAN),
        ("fsin(0x46000001u32)".to_string(), NAN), // just past the domain wall
        ("fcos(0u32)".to_string(), ONE),
        ("fcos(2147483648u32)".to_string(), ONE),
        (format!("fcos({NINF}u32)"), NAN),
        (format!("fcos({NAN}u32)"), NAN),
        ("fcos(0xC6000001u32)".to_string(), NAN),
        // fatan2: the IEEE special-value table (signs matter everywhere)
        (format!("fatan2(0u32, {ONE}u32)"), 0),
        (format!("fatan2(2147483648u32, {ONE}u32)"), 0x8000_0000),
        (format!("fatan2(0u32, {NEG_TWO}u32)"), 0x4049_0FDB), // +pi
        (format!("fatan2(2147483648u32, {NEG_TWO}u32)"), 0xC049_0FDB), // -pi
        (format!("fatan2({ONE}u32, 0u32)"), 0x3FC9_0FDB),     // +pi/2
        ("fatan2(0xBF800000u32, 0u32)".to_string(), 0xBFC9_0FDB), // -pi/2
        (format!("fatan2({INF}u32, {INF}u32)"), 0x3F49_0FDB), // +pi/4
        (format!("fatan2({INF}u32, {NINF}u32)"), 0x4016_CBE4), // +3pi/4
        (format!("fatan2(0xFF800000u32, {NINF}u32)"), 0xC016_CBE4), // -3pi/4
        (format!("fatan2({ONE}u32, {INF}u32)"), 0),
        (format!("fatan2({ONE}u32, {NINF}u32)"), 0x4049_0FDB),
        (format!("fatan2({NAN}u32, {ONE}u32)"), NAN),
        (format!("fatan2({ONE}u32, {ONE}u32)"), 0x3F49_0FDB), // exactly pi/4
    ];
    for (expr, want) in pins {
        let src = format!(
            "fn f() -> u16 {{ let mut bad = 0u16; if {expr} != {want}u32 {{ bad = 1u16; }} bad }}\n{}",
            rustz80::F32_KERNELS
        );
        assert_eq!(run_program_pruned(&src, "f"), 0, "{expr} != 0x{want:08X}");
    }
}

/// The typed f32 surface: `.exp()`/`.ln()`/`.powf()` route to the kernels through
/// the sugar (methods.rs), auto-appending them — checked behaviourally (identity
/// round-trip and a known power, within the declared bounds) since the sugar
/// world can't compare against raw u32 bit patterns by design.
#[test]
fn f32_trans_typed_surface() {
    // One program per method — all three families in one image would overrun the
    // classic code window (the same reason a sandboxed pow cell banks).
    let ln_src = r#"
fn f() -> u16 {
    let mut bad = 0u16;
    let x = 7.389056f32;
    let l = x.ln();
    if l > 2.0000005f32 { bad = bad + 1u16; }
    if l < 1.9999995f32 { bad = bad + 1u16; }
    bad
}
"#;
    let exp_src = r#"
fn f() -> u16 {
    let mut bad = 0u16;
    let e = 1.0f32.exp();
    if e > 2.7182823f32 { bad = bad + 1u16; }
    if e < 2.7182813f32 { bad = bad + 1u16; }
    bad
}
"#;
    let pow_src = r#"
fn f() -> u16 {
    let mut bad = 0u16;
    let b = 2.0f32;
    let p = b.powf(3.0f32);
    if p > 8.0001f32 { bad = bad + 1u16; }
    if p < 7.9999f32 { bad = bad + 1u16; }
    bad
}
"#;
    assert_eq!(run_program_pruned(ln_src, "f"), 0, "ln");
    assert_eq!(run_program_pruned(exp_src, "f"), 0, "exp");
    assert_eq!(
        run_program_banked(pow_src, "f"),
        0,
        "powf (banked — inline overruns)"
    );
}

/// Bank bit-invisibility: the F2 kernels are NOT bank members (residency is a
/// deliberate, deferred rebank event — softfloat.rs), but a banked cell calling
/// them must produce identical bits: the kernels append locally and their
/// `fadd`/`fmul` calls resolve into the bank.
#[test]
fn f32_trans_banked_is_bit_invisible() {
    let banks = load();
    for b in &banks {
        for (args, sim, _) in b.cases.iter().step_by(97) {
            let body = format!(
                "fn f() -> u16 {{ let mut bad = 0u16; if {} != {sim}u32 {{ bad = 1u16; }} bad }}\n{}",
                call_expr(b.name, args),
                rustz80::F32_KERNELS
            );
            assert_eq!(
                run_program_banked(&body, "f"),
                0,
                "banked {}({args:08X?}) diverged from the pruned path",
                b.name
            );
        }
    }
}

/// The explicit bit reinterprets (`f32_from_bits`/`f32_to_bits`): zero-cost,
/// loud-by-name, round-trip exact — the `u32[N]`-of-f32-bits envelope's reader.
#[test]
fn f32_bit_reinterprets_round_trip() {
    let src = r#"
fn f() -> u16 {
    let mut bad = 0u16;
    let x = f32_from_bits(0x40490FDBu32);
    if x > 3.1415929f32 { bad = bad + 1u16; }
    if x < 3.1415925f32 { bad = bad + 1u16; }
    if f32_to_bits(x) != 0x40490FDBu32 { bad = bad + 1u16; }
    let y = f32_from_bits(f32_to_bits(2.5f32) + 0u32);
    if y != 2.5f32 { bad = bad + 1u16; }
    bad
}
"#;
    assert_eq!(run_program_pruned(src, "f"), 0);
}
