//! The **earn-in gate** for [`ValueHeuristic`] — learned vs hand heuristic at equal budget,
//! on outcome-specified synthesis over the lossy real-library cells.
//!
//! Run: `cargo run --release --example synth_value_gate -p cell80`
//!
//! `synthesize` ships with the hand Hamming heuristic; the learned value heuristic is
//! **gated** — it earns its place per op-family only by beating hand at equal node budget
//! here. Pre-registered (before the first run, tie band ±3 pts, report raw either way):
//!
//! - **EARNS IN**: learned beats hand by > 3 pts at every budget where blind (h = 0)
//!   solves < 90% — the shape of the reproduced B3′ result (chuk-soma
//!   `experiments/setb/value_search.rs`: bins net 30→83% vs Hamming 13→62%).
//! - **STAYS GATED**: anything else. No post-hoc variations.
//!
//! Tasks are the synthesis product shape: a hidden chain over the op family, seen only as
//! input→output **examples** (3 per task) — the chain must be discovered through the
//! [`synthesize_with`] seam over the *joint* example state. The value net is trained on
//! single-pair distances from the op tables (disjoint seed) and applied summed over the
//! examples, exactly as the hand Hamming heuristic sums per-example bit distance.

use std::cell::RefCell;
use std::collections::HashMap;

use cell80::{
    synthesize, synthesize_with, Cartridge, CartridgeOpts, CellConfig, Op, ValueHeuristic,
    ValueTrainConfig,
};

const HIDDEN_CHAIN: usize = 8;
const EXAMPLES: usize = 3;
const TASKS: usize = 60;
const MAX_DEPTH: usize = 10;
const BUDGETS: [usize; 5] = [250, 500, 1000, 2000, 4000];
const BAND: f32 = 3.0;

struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
    fn u16(&mut self) -> u16 {
        (self.next() & 0xFFFF) as u16
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n.max(1) as u64) as usize
    }
}

fn op(src: &str, id: &str, arg: u16) -> Op {
    let cart = Cartridge::compile(
        src,
        CellConfig::sandboxed(),
        CartridgeOpts {
            id: Some(id.into()),
            ..Default::default()
        },
    )
    .unwrap_or_else(|e| panic!("compile {id}: {e}"));
    Op::from_cell(id, &cart, arg)
}

/// The lossy bit-op family from the real cell library (AND/OR destroy bits, rotate/swap/
/// reverse scramble Hamming) — the deceptive regime synthesis exists for.
fn ops() -> Vec<Op> {
    vec![
        op(
            include_str!("../cells/mask_intersection.rs"),
            "and_ff00",
            0xFF00,
        ),
        op(
            include_str!("../cells/mask_intersection.rs"),
            "and_0ff0",
            0x0FF0,
        ),
        op(include_str!("../cells/mask_union.rs"), "or_00ff", 0x00FF),
        op(include_str!("../cells/mask_union.rs"), "or_0f0f", 0x0F0F),
        op(include_str!("../cells/mask_xor.rs"), "xor_0f0f", 0x0F0F),
        op(include_str!("../cells/mask_xor.rs"), "xor_f0f0", 0xF0F0),
        op(include_str!("../cells/toggle_bit.rs"), "toggle_0", 0),
        op(include_str!("../cells/toggle_bit.rs"), "toggle_7", 7),
        op(include_str!("../cells/toggle_bit.rs"), "toggle_15", 15),
        op(include_str!("../cells/rotl16.rs"), "rol_4", 4),
        op(include_str!("../cells/swap_bytes.rs"), "swap", 0),
        op(include_str!("../cells/reverse_bits.rs"), "rev", 0),
    ]
}

/// One outcome-specified task: examples generated by a hidden random chain (a witness of
/// length `HIDDEN_CHAIN` exists by construction). Non-trivial displacement required.
fn gen_task(rng: &mut Rng, ops: &[Op]) -> Vec<(u16, u16)> {
    loop {
        let chain: Vec<usize> = (0..HIDDEN_CHAIN).map(|_| rng.below(ops.len())).collect();
        let examples: Vec<(u16, u16)> = (0..EXAMPLES)
            .map(|_| {
                let x = rng.u16();
                let mut v = x;
                for &i in &chain {
                    v = ops[i].apply(v);
                }
                (x, v)
            })
            .collect();
        let displaced: u32 = examples.iter().map(|&(x, y)| (x ^ y).count_ones()).sum();
        if displaced >= 12 {
            return examples;
        }
    }
}

fn main() {
    let ops = ops();
    println!("training the value heuristic on the op family (one-time, per-family cost)…");
    let vh = ValueHeuristic::train(&ops, &ValueTrainConfig::default());
    println!("held-out value MAE: {:.2} steps\n", vh.held_out_mae);

    let mut rng = Rng(0xEA61); // disjoint from the training seed
    let tasks: Vec<Vec<(u16, u16)>> = (0..TASKS).map(|_| gen_task(&mut rng, &ops)).collect();

    let pct = |hits: usize| 100.0 * hits as f32 / TASKS as f32;
    println!(
        "solved % over {TASKS} outcome-specified tasks (hidden {HIDDEN_CHAIN}-op chains, {EXAMPLES} examples each), by expansion budget:\n"
    );
    println!(
        "  {:>7}  {:>10}  {:>12}  {:>13}",
        "budget", "blind(h=0)", "hand Hamming", "learned value"
    );
    println!("  {}", "-".repeat(50));

    let mut rows: Vec<(f32, f32, f32)> = Vec::new();
    for &b in &BUDGETS {
        let blind = pct(tasks
            .iter()
            .filter(|ex| synthesize_with(ex, &ops, MAX_DEPTH, b, &|_, _| 0).is_some())
            .count());
        let hand = pct(tasks
            .iter()
            .filter(|ex| synthesize(ex, &ops, MAX_DEPTH, b).is_some())
            .count());
        // Memoise per-pair values (same numbers, fewer forwards — compute parity is the
        // node budget, unchanged).
        let learned = pct(tasks
            .iter()
            .filter(|ex| {
                let memo: RefCell<HashMap<(u16, u16), i64>> = RefCell::new(HashMap::new());
                let h = |s: &[u16], t: &[u16]| -> i64 {
                    s.iter()
                        .zip(t)
                        .map(|(&si, &ti)| {
                            *memo
                                .borrow_mut()
                                .entry((si, ti))
                                .or_insert_with(|| vh.h(&[si], &[ti]))
                        })
                        .sum()
                };
                synthesize_with(ex, &ops, MAX_DEPTH, b, &h).is_some()
            })
            .count());
        println!("  {b:>7}  {blind:>9.1}%  {hand:>11.1}%  {learned:>12.1}%");
        rows.push((blind, hand, learned));
    }

    let bounded: Vec<&(f32, f32, f32)> = rows.iter().filter(|r| r.0 < 90.0).collect();
    let earns_in = !bounded.is_empty() && bounded.iter().all(|r| r.2 - r.1 > BAND);
    println!(
        "\nGATE ({} bounded budgets, tie band ±{BAND}): the learned value heuristic {}",
        bounded.len(),
        if earns_in {
            "EARNS IN for this op family (beats hand at every bounded budget)"
        } else {
            "STAYS GATED (does not beat hand at every bounded budget — ship hand-first)"
        }
    );
}
