//! Demo of the experimental **synthesis** surface — the inverse of `CellGraph`.
//!
//! Run: `cargo run --release --example synth_demo -p cell80`
//!
//! You give input→output **examples** (not the steps); synthesis discovers a short chain of
//! cells that reproduces them, verified by execution. The op-set here is lossy bit/mask ops —
//! the regime where this mode is genuinely needed (distance-greedy is deceptive, so it can't
//! be folded into "read the steps and run them"). Heuristic-first: A* over the verifier with
//! the hand Hamming heuristic (a learned value net would enter only *gated* — see the
//! composition_eval kill gate, where it merely tied this).
use cell80::{synthesize, Cartridge, CartridgeOpts, CellConfig, Op};

fn cell(id: &str, src: &str) -> Cartridge {
    Cartridge::compile(
        src,
        CellConfig::sandboxed(),
        CartridgeOpts {
            id: Some(id.into()),
            ..Default::default()
        },
    )
    .unwrap_or_else(|e| panic!("compile {id}: {e}"))
}

fn ops() -> Vec<Op> {
    let xor = cell("mask_xor", include_str!("../cells/mask_xor.rs"));
    let and = cell(
        "mask_intersection",
        include_str!("../cells/mask_intersection.rs"),
    );
    let or = cell("mask_union", include_str!("../cells/mask_union.rs"));
    let swap = cell("swap_bytes", include_str!("../cells/swap_bytes.rs"));
    let rotl = cell("rotl16", include_str!("../cells/rotl16.rs"));
    vec![
        Op::from_cell("xor_00ff", &xor, 0x00FF),
        Op::from_cell("xor_ff00", &xor, 0xFF00),
        Op::from_cell("and_0ff0", &and, 0x0FF0),
        Op::from_cell("or_f00f", &or, 0xF00F),
        Op::from_cell("swap", &swap, 0),
        Op::from_cell("rotl4", &rotl, 4),
    ]
}

/// Apply a named chain to a value (to show the verifier confirms the discovered plan).
fn run_chain(ops: &[Op], steps: &[String], mut v: u16) -> u16 {
    for s in steps {
        v = ops.iter().find(|o| &o.name == s).unwrap().apply(v);
    }
    v
}

fn demo(ops: &[Op], title: &str, hidden: &[&str], probes: &[u16]) {
    // Build the spec: input→output examples generated by a HIDDEN chain (not given to search).
    let examples: Vec<(u16, u16)> = probes
        .iter()
        .map(|&x| (x, run_chain(ops, &to_owned(hidden), x)))
        .collect();
    println!("\n● {title}");
    println!("  hidden program (not given): {hidden:?}");
    print!("  examples:");
    for (x, y) in &examples {
        print!(" {x:#06x}->{y:#06x}");
    }
    println!();
    match synthesize(&examples, ops, 5, 200_000) {
        Some(plan) => {
            let ok = examples
                .iter()
                .all(|&(x, y)| run_chain(ops, &plan.steps, x) == y);
            println!(
                "  FOUND  steps={:?}  depth={}  tested={}  verified={}",
                plan.steps, plan.depth, plan.tested, ok
            );
        }
        None => println!("  no chain found within budget"),
    }
}

fn to_owned(v: &[&str]) -> Vec<String> {
    v.iter().map(|s| s.to_string()).collect()
}

fn main() {
    let ops = ops();
    println!("Synthesis demo — examples → CellGraph chain (inverse of CellGraph)");
    // Synthesis discovers *a* chain reproducing the examples — not necessarily the hidden one.
    demo(
        &ops,
        "byte-swap then low-byte flip",
        &["swap", "xor_00ff"],
        &[0x1234, 0x00FF, 0xABCD, 0x0102],
    );
    demo(
        &ops,
        "mask then rotate",
        &["and_0ff0", "rotl4"],
        &[0x1234, 0xFFFF, 0x0F0F, 0x8001],
    );
    demo(
        &ops,
        "single op (low flip)",
        &["xor_00ff"],
        &[0x1234, 0xABCD],
    );

    // An honest negative: one input required to map to two different outputs — unsatisfiable.
    println!("\n● unsatisfiable spec (same input, two outputs)");
    match synthesize(&[(0x10, 0x20), (0x10, 0x30)], &ops, 5, 50_000) {
        Some(p) => println!("  unexpectedly found {:?}", p.steps),
        None => {
            println!("  correctly found NO chain (a function can't map one input to two outputs)")
        }
    }
}
